Public Class fHelp	Private Sub Rtf_MouseDown(sender As Object, e As MouseEventArgs) Handles Rtf.MouseDown		If Rtf.ReadOnly Then GeserForm(Me)	End Sub	Private Sub Rtf_TextChanged(sender As Object, e As EventArgs) Handles Rtf.TextChanged		SetProc("update tHelp set " & lHelp.Text & " ='" & Rtf.Rtf & "'  ")	End Sub	Private Sub fHelp_Disposed(sender As Object, e As EventArgs) Handles Me.Disposed		SetPosisiForm(Me)	End Sub	Sub TampilData()		Rtf.Text = GetProc("select " & lHelp.Text & " from tHelp")		If Rtf.Text = "" Then : SetProc("insert into " & lHelp.Text & " (tHelp) values('" & Rtf.Rtf & "') ")		Else : Rtf.Rtf = Rtf.Text : End If		Rtf.BorderStyle = IIf(Rtf.ReadOnly, BorderStyle.None, BorderStyle.Fixed3D)	End Sub	Private Sub fHelp_Shown(sender As Object, e As EventArgs) Handles Me.Shown		TampilData()		If Me.Tag = "awal" Then			Me.Width = 300			Me.Height = 555			Me.Location = New Point(RJ_First.Width - 300, 100)		End If	End Sub	Private Sub fHelp_Load(sender As Object, e As EventArgs) Handles MyBase.Load		GetPosisiForm(Me)		If Me.Left > RJ_First.Left + RJ_First.Width + Me.Width Then Me.Left = (RJ_First.Left + RJ_First.Width) - Me.Width		Dim isiHelp As Int16 = GetProc("select count(Help)as jml from thelp")		If isiHelp = 0 Then			SetProc("insert into thelp values('','')")		End If	End Sub	Private Sub fHelp_MouseDown(sender As Object, e As MouseEventArgs) Handles Me.MouseDown		GeserForm(Me)	End Sub	Private Sub fHelp_KeyDown(sender As Object, e As KeyEventArgs) Handles Me.KeyDown		If e.KeyCode = Keys.Escape Then Me.Dispose() : Exit Sub		If e.Control And e.KeyCode = Keys.F12 Then			Rtf.ReadOnly = Not Rtf.ReadOnly			Rtf.BorderStyle = IIf(Rtf.ReadOnly, BorderStyle.None, BorderStyle.Fixed3D)		End If		If e.Control And e.KeyCode = Keys.U Then lHelp.Text = "KetUpdate" : TampilData()		If e.Control And e.KeyCode = Keys.H Then lHelp.Text = "Help" : TampilData()	End Sub

	'Private Sub ZoomT_EditValueChanged(sender As Object, e As EventArgs) Handles ZoomT.EditValueChanged
	'    Me.Opacity = ZoomT.Value / 100
	'End Sub

	'Private Sub fHelp_Resize(sender As Object, e As EventArgs) Handles Me.Resize
	'    ZoomT.Top = (Me.Height / 2) - (ZoomT.Height / 2)
	'End Sub
End Class